locale: "en_US.UTF-8"
timezone: "Etc/UTC"

server_ip: "138.201.120.72"

dashboard_port: 8083

clean_hour: "0"

perfsuite_hour: "1"
perfsuite_aggregate_hour: "6"
perfsuite_online_hour: "6"
perfsuite_port: "8082"

certifsuite_hour: "5"
certifsuite_port: "8080"

certification_hour: "6"

qwc2_hour: "6"
qwc2_port: "8081"

ogcapif_hour: "6"
ogcapif_port: "8084"

user: "qgis-server-admin"

mail_addresses:
- blottiere.paul@gmail.com
- eric.lemoine@gmail.com
